name: CI

on:
  push:
    branches:
      - 'master'
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/rust.yml'
  pull_request:
    paths:
      - '**.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/rust.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Rust latest stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: check dependencies
        run: cargo check --all-targets
      - name: run "cargo deny check"
        uses: EmbarkStudios/cargo-deny-action@v2.0.4

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Rust latest stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy,rustfmt
      - name: run rustfmt
        run: cargo fmt --all -- --check
      - name: run clippy
        run: cargo clippy --all-targets -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Rust latest stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: run tests
        run: cargo test --all-targets
